apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: nncp-workers-bond0-vlan2124
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  desiredState:
    interfaces:
    - name: bond0.2124
      description: VLAN 2124 using bond0
      type: vlan
      state: up
      vlan:
        base-iface: bond0
        id: 2124
      mtu: 9000
